# Workflow para build e deploy de um site Next.js no GitHub Pages
name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"] # Altere para 'master' se for o caso
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          # CORREÇÃO: Aponta para o local correto do seu package-lock.json
          cache-dependency-path: project/package-lock.json

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        # CORREÇÃO: Executa o npm install dentro da pasta /project
        working-directory: ./project
        run: npm install

      - name: Build Static Site
        # CORREÇÃO: Executa o build dentro da pasta /project
        working-directory: ./project
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Create .nojekyll file
        # CORREÇÃO: Cria o arquivo na pasta de saída correta
        working-directory: ./project
        run: touch ./out/.nojekyll

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # CORREÇÃO: Aponta para a pasta de saída (out) dentro de /project
          path: "./project/out"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4